### ISSUE TITLE
Enhancement: Authelia user group name

### ISSUE THREAD

**Issue by cellulosa** [nikarh/jellyfin-plugin-authelia#54]
heya thanks for the great plugin.

If I may recommend an enhancement, it'd be great to have a `Authelia user group name` so that only users assigned to - let's say group jellyfin_user - are allowed to login.

**Comment by nikarh** [comment]
Hi!

The thing you want to achieve is already doable, but via a slightly different mechanism.
You can restrict access by groups just with the Authelia configuration:

```yaml
access_control:
  rules:
  - domain:
    - jellyfin.yourdomain.com # This is the domain that you enter in the plugins configuration, field from the screenshot
    policy: one_factor
    subject:
    - "group:media" # This is the group, only users that are in this group are allowed to log in in Jellyfin
```
![image](https://github.com/nikarh/jellyfin-plugin-authelia/assets/5517011/79375601-69c0-466b-bfb4-2976ad104213)
