### ISSUE TITLE
Adding required authz to Authelia breaks everying else

### ISSUE THREAD

**Issue by spmp** [nikarh/jellyfin-plugin-authelia#75]
This is a very promising looking plugin. I am very new to the world of Authelia/LDAP etc. so please be kind 8)

I have tried using this plugin with no success, but more importantly adding the required 
```
server:
    endpoints:
        authz:
            auth-request:
                implementation: 'AuthRequest'
```
completely wrecks the rest of Authelia. i.e none of my other hosts work anymore and are filtered without log message even when set to debug.

Would you be able to provide details for how a complete novice/f00l could setup this plugin which would allow for proxied hosts to continue to work etc.

I am using the latest traefik, Authelia, and Jellyfin from docker.

Thank you.

**Comment by spmp** [comment]
Wow, it's just working, even with that option disabled! Nice. Solved
For completeness, here is the config `Authelia-Auth.xml` where Authelia is running in a container named `auth` and Jellyfin is in a container named `jellyfin`, both behind traefik.

```xml
<?xml version="1.0" encoding="utf-8"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <AutheliaServer>https://auth.example.com</AutheliaServer>
  <AutheliaRootCa />
  <AutheliaAdminGroup>admins</AutheliaAdminGroup>
  <CreateUserIfNotExists>true</CreateUserIfNotExists>
  <JellyfinUrl>https://jellyfin.example.com</JellyfinUrl>
</PluginConfiguration>
```

And in Authelia I needed to make sure that the domain was accessible to users:

```yml
access_control:
  rules:
    - domain:
        - "jellyfin.example.com"
      subject:
        - "group:jellyfin-users"
      policy: one_factor
```

Where the user is a member of  `jellyfin-users`. If they are a member of `admin` the admin privilege is working properly. Nice.

```yml
  johnd:
    displayname: "John Doe"
    password: "somehash"
    email: jd@example.com
    groups:
      - jellyfin-users
```
